python chandra/obsids.py /home/rdave/chandradata/Proposal/1.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1002.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1007.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1011.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1017.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1018.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/102.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1020.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1022.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1025.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1033.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1038.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/104.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1042.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1043.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1055.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1058.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1065.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1079.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1081.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1082.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1083.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1084.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1085.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1086.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1089.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/109.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1100.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1105.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/113.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1131.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1136.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1148.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/116.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1161.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1163.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1171.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1176.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1178.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1184.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/119.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1194.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/12.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/120.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1206.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/121.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/122.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1227.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1235.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1236.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1238.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1240.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1241.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1248.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1251.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1257.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1259.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1260.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1263.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1264.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1265.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1266.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1268.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/127.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1271.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1272.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1273.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1275.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1276.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1277.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1279.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1280.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1281.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1283.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1285.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1288.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1291.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1295.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1297.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1299.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/130.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1303.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1308.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/131.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1312.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1314.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1316.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1317.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1318.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1341.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1355.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1377.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1381.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1391.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1406.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1407.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1409.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/141.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1427.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/143.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1444.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1462.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1463.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1470.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1474.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1480.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1481.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1482.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1483.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1487.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1489.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/149.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1490.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1491.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1493.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1494.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1495.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1497.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1499.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/15.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1505.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1507.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1514.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1520.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1521.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1524.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1526.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1528.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1535.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1538.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1541.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1542.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1543.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1552.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1563.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1566.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1573.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1579.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1581.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1593.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1594.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1595.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1596.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1599.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1618.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/164.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1644.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/165.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1659.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1684.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1698.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/17.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/170.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1728.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1735.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1741.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1743.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1744.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1747.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1748.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/175.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1753.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1759.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1764.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1765.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1799.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/18.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/181.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1811.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1812.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1819.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1820.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1824.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1826.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1843.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1844.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1847.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/185.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1854.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1858.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1870.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1871.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1872.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1875.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1893.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1894.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1897.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/191.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/192.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/193.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/195.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1976.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1979.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1985.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1989.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/199.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/1997.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/200.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2000.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2003.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2007.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2009.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2011.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2015.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/202.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2020.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2022.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2023.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/203.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2033.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2035.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/205.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2053.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2054.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2055.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2056.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2058.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2061.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2062.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2077.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2082.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2086.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/21.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2109.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2118.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2122.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2123.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2171.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2187.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2197.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/220.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2207.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2208.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2220.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2225.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2234.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2242.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2243.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2245.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2248.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2249.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/225.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2259.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2260.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/229.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2298.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/23.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2302.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2310.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2313.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2355.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/238.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/239.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2424.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2437.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2439.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/245.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2485.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2487.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2508.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2515.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/252.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2574.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/258.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/260.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/262.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2625.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/263.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/266.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/273.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/275.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/278.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/279.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/280.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/281.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/282.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/283.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/285.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/286.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/289.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/291.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/292.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2926.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/293.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/294.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/296.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/297.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/2971.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/298.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/299.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/3.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/301.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/303.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/306.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/307.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/308.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/310.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/311.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/312.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/313.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/314.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/315.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/317.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/318.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/322.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/325.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/331.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/332.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/335.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/336.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/337.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/338.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/34.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/340.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/341.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/345.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/354.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/356.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/36.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/362.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/386.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/387.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/422.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/427.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/445.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/446.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/462.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/463.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/466.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/469.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/471.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/472.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/474.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/475.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/476.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/479.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/480.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/481.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/482.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/486.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/487.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/489.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/490.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/491.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/494.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/497.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/499.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/50.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/502.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/505.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/506.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/508.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/512.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/52.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/520.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/522.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/524.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/525.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/527.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/53.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/530.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/533.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/54.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/545.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/55.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/553.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/554.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/557.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/561.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/57.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/572.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/573.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/579.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/585.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/59.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/6.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/60.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/602.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/610.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/611.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/616.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/62.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/621.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/623.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/626.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/627.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/628.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/630.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/632.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/633.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/634.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/636.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/637.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/638.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/639.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/64.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/640.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/641.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/643.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/645.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/646.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/647.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/648.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/649.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/650.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/651.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/652.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/654.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/656.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/657.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/662.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/663.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/664.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/665.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/667.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/668.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/669.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/671.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/673.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/674.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/677.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/678.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/679.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/686.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/688.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/69.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/691.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/698.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/7.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/70.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/701.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/703.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/705.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/707.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/71.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/711.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/714.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/72.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/726.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/729.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/754.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/759.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/767.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/779.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/78.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/790.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/795.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/796.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/799.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/800.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/807.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/809.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/819.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/82.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/827.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/839.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/84.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/841.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/845.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/850.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/86.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/860.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/868.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/871.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/872.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/873.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/874.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/877.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/880.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/884.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/885.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/889.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/890.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/891.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/892.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/893.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/895.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/898.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/899.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/900.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/902.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/904.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/905.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/906.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/910.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/915.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/919.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/921.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/924.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/925.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/926.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/928.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/93.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/930.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/932.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/935.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/937.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/938.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/939.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/94.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/942.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/944.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/945.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/946.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/949.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/95.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/950.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/951.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/955.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/96.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/961.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/963.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/970.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/977.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/986.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/988.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/993.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/994.xml prop
python chandra/obsids.py /home/rdave/chandradata/Proposal/996.xml prop
