#!/bin/bash

export PYTHONPATH=/proj/ads/soft/python/lib/site-packages/
mission=$1
module=$2
grep ERROR ${mission}/prelim.${module}.simbad.dict >> ${mission}/error.${module}.simbad 
grep -v ERROR ${mission}/prelim.${module}.simbad.dict > ${mission}/${module}.simbad.dict
